version: '2.2'

services:
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zoo
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: test-topic-1:1:1
      # add advertised host to machine hosts file to connect from outside tooling
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper:2181
    networks:
      svc-kafka-ui-network:
        aliases:
          - kafka-broker

  zoo:
    image: elevy/zookeeper:latest
    environment:
      MYID: 1
      SERVERS: zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    networks:
      svc-kafka-ui-network:
        aliases:
          - zookeeper

networks:
  svc-kafka-ui-network:
    internal: false